---
title: "EDRM 718 Final Exam"
author: "Ningqiao Li"
date: "May 4th, 2020"
output: html_notebook
---


This is final exam report of EDRM 718 created by Ningqiao Li

***

### 1. Tidy the data and merge them into one csv file.
#### 1.1 Tidy the Job Prep Demographics

demographics <- read_csv("Job Prep Demographics.csv", skip = 4,
                         col_types = cols(HUMANITIES = col_double(),
                                          X2 = col_double(),
                                          X3 = col_double(),
                                          X4 = col_factor()))
View(demographics)
demographics$X5 <- NULL

demographics1 <- demographics %>%
  filter(between(row_number(), 3, 140)) %>%
  mutate(discipline = "Humanities")

demographics2 <- demographics %>%
  filter(between(row_number(), 146, 298)) %>%
  mutate(discipline = "SocialSci")

demographics3 <- demographics %>%
  filter(between(row_number(), 304, 458)) %>%
  mutate(discipline = "NaturalSci")

demographics4 <- demographics %>%
  filter(between(row_number(), 464, 612)) %>%
  mutate(discipline = "FormalSci")

demographics5 <- demographics %>%
  filter(between(row_number(), 618, 761)) %>%
  mutate(discipline = "AppliedSci") 

newdemo <- rbind(demographics1, demographics2, demographics3, demographics4, demographics5)  
colnames(newdemo) = c("ID", "SchoolCode", "Age", "Gender", "Discipline") 
  
(newdemo <- newdemo %>%
  arrange(ID))


#1.2 Tidy the Job Prep GPA Data
GPA <- read_csv("Job Prep GPA Data.csv", skip = 5,
                col_names = c("ID", "SchoolCode", "Age", "Gender", 
                             "CreditsS1", "GPAS1", "CreditsS2", "GPAS2"))
(GPA <- GPA %>%
    arrange(ID))

#1.3 Join the two datasets
merge1 <- GPA %>%
  left_join(newdemo, c("ID" = "ID", "SchoolCode" = "SchoolCode", "Age" = "Age", "Gender" = "Gender"))

#1.4 Tidy the Job Prep Survey Results
survey <- read_csv("Job Prep Survey Results.csv", skip = 3)
newsurvey <- new_survey_data(survey, 6, c(5, 10, 13, 14))  # employ the new_survey_data function to account for reverse score.
newsurvey
newsurvey[, 2:15] <- NULL
newsurvey

#1.5 Merge the survey data to the merge1 dataset, thus all three original datasets are tidy and merged into one dataset.
(tidydata <- newsurvey %>%
  left_join(merge1, c("ID" = "ID")) %>%
    arrange(ID))

tidydata <- tidydata %>%
  rename(Optimism = Sum)
tidydata

# check for NA data
colSums(is.na(tidydata))
(tidydata <- tidydata %>%
  drop_na(SchoolCode))

